version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: people_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: people_db
      TZ: Asia/Kolkata
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [appnet]

  api:
    build: ./backend
    container_name: people_api
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: people_db
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "5000"
    restart: unless-stopped
    networks: [appnet]

  web:
    build: ./web
    container_name: people_web
    depends_on:
      - api
    ports:
      - "80:80"           # open this in EC2 SG
    restart: unless-stopped
    networks: [appnet]

volumes:
  db_data:

networks:
  appnet:
